trigger:
  batch: true
  branches:
    include:
      - master
      - dev/PowerLauncher
  paths:
    exclude:
      - doc/*
      - temp/*
      - tools/*

pr:
  branches:
    include:
      - master
      - dev/PowerLauncher

#     0.0.yyMM.dd##
#     0.0.1904.0900
name: 0.0.$(Date:yyMM).$(Date:dd)$(Rev:rr)

jobs:
  - template: ./templates/build-powertoys-ci.yml
    parameters:
      platform: x64
